
eureka:
  instance:
      prefer-ip-address: true
      #instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: joinx-01-eurekaprovider
server:
  port: 8888
joinx-03-eurekaprovider:
  ribbon:
   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
